package com.zee.android.eventbus.utils
/**
 * register setting
 * @author billy.qi email: qiyilike@163.com
 * @since 17/3/28 11:48
 */
class ScanSetting {
    static final String PLUGIN_NAME = "com.zee.ZxRouter"

    /**
     * you know. this is the class file(or entry in jar file) name
     */
    static final String GENERATE_TO_CLASS_FILE_NAME = 'com/zee/utils/ZConfig.class'
    /**
     * The register code is generated into this method
     */
    static final String GENERATE_TO_METHOD_NAME = 'addRegisterData'

    static final String REGISTER_METHOD_NAME = 'register'

    /**
     * The package name of the interfaces
     */
    private static final INTERFACE_PACKAGE_NAME = 'org/greenrobot/eventbus/interfaces/'

    /**
     * The package name of the class generated by the annotationProcessor
     */
    static final String ROUTER_CLASS_PACKAGE_NAME = 'com/zee/temp/'

    /**
     * scan for classes which implements this interface
     */
    String interfaceName = ''

    /**
     * scan result for {@link #interfaceName}
     * class names in this list
     */
    ArrayList<String> classList = new ArrayList<>()

    /**
     * constructor for EventBus-auto-register settings
     * @param interfaceName interface to scan
     */
    ScanSetting(String interfaceName) {
        this.interfaceName = INTERFACE_PACKAGE_NAME + interfaceName
    }

}